[{
  "kind": "youtube#searchResult",
  "etag": "paxmZlrwLklpBMv5cseM7UPC-Js",
  "id": { "kind": "youtube#video", "videoId": "EQCc1cNmvfw" },
  "snippet": {
    "publishedAt": "2026-01-05T16:00:25Z",
    "channelId": "UClkc3m-0-ZFIqf1gBymlcUA",
    "title": "CHAQUETA REVIT GT-R AIR 3 / Chaqueta deportiva de verano, disponible en www.motomundi.cl",
    "description": "Deseas leer los detalles del producto o incluso comprarlo? Revisa el siguiente link: ...",
    "thumbnails": {
      "default": { "url": "https://i.ytimg.com/vi/EQCc1cNmvfw/default.jpg", "width": 120, "height": 90 },
      "medium": { "url": "https://i.ytimg.com/vi/EQCc1cNmvfw/mqdefault.jpg", "width": 320, "height": 180 },
      "high": { "url": "https://i.ytimg.com/vi/EQCc1cNmvfw/hqdefault.jpg", "width": 480, "height": 360 },
    },
    "channelTitle": "MotoMundiTv",
    "liveBroadcastContent": "none",
    "publishTime": "2026-01-05T16:00:25Z",
  },
}, {
  "kind": "youtube#searchResult",
  "etag": "dL_LTNqysCC0kzmhARxBP9M9b84",
  "id": { "kind": "youtube#video", "videoId": "Nt9EjnfT8kM" },
  "snippet": {
    "publishedAt": "2026-01-05T16:00:40Z",
    "channelId": "UClkc3m-0-ZFIqf1gBymlcUA",
    "title": "GUANTE REVIT ACCESS / Guante de verano urbano, disponible en motomundi.cl",
    "description": "Deseas leer los detalles del producto o incluso comprarlo? Revisa el siguiente link: ...",
    "thumbnails": {
      "default": { "url": "https://i.ytimg.com/vi/Nt9EjnfT8kM/default.jpg", "width": 120, "height": 90 },
      "medium": { "url": "https://i.ytimg.com/vi/Nt9EjnfT8kM/mqdefault.jpg", "width": 320, "height": 180 },
      "high": { "url": "https://i.ytimg.com/vi/Nt9EjnfT8kM/hqdefault.jpg", "width": 480, "height": 360 },
    },
    "channelTitle": "MotoMundiTv",
    "liveBroadcastContent": "none",
    "publishTime": "2026-01-05T16:00:40Z",
  },
}, {
  "kind": "youtube#searchResult",
  "etag": "g8kadAPDDXe3_4oedMabTQgocYo",
  "id": { "kind": "youtube#video", "videoId": "GfdzrnuPmVo" },
  "snippet": {
    "publishedAt": "2026-01-05T16:00:35Z",
    "channelId": "UClkc3m-0-ZFIqf1gBymlcUA",
    "title": "GUANTE REVIT SPEEDART AIR / Guante de verano, disponible en motomundi.cl",
    "description": "Deseas leer los detalles del producto o incluso comprarlo? Revisa el siguiente link: ...",
    "thumbnails": {
      "default": { "url": "https://i.ytimg.com/vi/GfdzrnuPmVo/default.jpg", "width": 120, "height": 90 },
      "medium": { "url": "https://i.ytimg.com/vi/GfdzrnuPmVo/mqdefault.jpg", "width": 320, "height": 180 },
      "high": { "url": "https://i.ytimg.com/vi/GfdzrnuPmVo/hqdefault.jpg", "width": 480, "height": 360 },
    },
    "channelTitle": "MotoMundiTv",
    "liveBroadcastContent": "none",
    "publishTime": "2026-01-05T16:00:35Z",
  },
}]
