name: Remote Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted # This targets your Windows 2012 server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          pnpm install
          pnpm run build
          cp ..\web.config .
