export const COUNTRIES = [
  {
    code: 'CL', name: 'Chile', flag: '🇨🇱', dialCode: '+56',
    idTypes: [{ value: 'RUT', label: 'RUT' }],
    idPlaceholder: '12.345.678-9',
    idMask: 'rut',
    stateLabel: 'Región',
    cityLabel: 'Ciudad / Comuna',
    postalCodeLabel: 'Código postal',
    hasPostalCode: false,
    addressLine2Label: 'Depto / Casa / Oficina',
    states: [
      'Arica y Parinacota',
      'Tarapacá',
      'Antofagasta',
      'Atacama',
      'Coquimbo',
      'Valparaíso',
      'Metropolitana de Santiago',
      'O\'Higgins',
      'Maule',
      'Ñuble',
      'Biobío',
      'La Araucanía',
      'Los Ríos',
      'Los Lagos',
      'Aysén',
      'Magallanes',
    ],
  },
  {
    code: 'AR', name: 'Argentina', flag: '🇦🇷', dialCode: '+54',
    idTypes: [
      { value: 'DNI', label: 'DNI' },
      { value: 'CUIT', label: 'CUIT / CUIL' },
      { value: 'PASAPORTE', label: 'Pasaporte' },
    ],
    idPlaceholder: '12 345 678',
    idMask: 'numeric',
    stateLabel: 'Provincia',
    cityLabel: 'Ciudad',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Piso / Depto',
    states: [
      'Buenos Aires',
      'CABA',
      'Catamarca',
      'Chaco',
      'Chubut',
      'Córdoba',
      'Corrientes',
      'Entre Ríos',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquén',
      'Río Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucumán',
    ],
  },
  {
    code: 'BR', name: 'Brasil', flag: '🇧🇷', dialCode: '+55',
    idTypes: [
      { value: 'CPF',       label: 'CPF'            },  // natural persons
      { value: 'CNPJ',      label: 'CNPJ'           },  // legal entities
      { value: 'RG',        label: 'RG'             },  // state ID card
      { value: 'PASAPORTE', label: 'Passaporte'     },
    ],
    idPlaceholder: '123.456.789-09',   // CPF format
    idMask: 'numeric',
    stateLabel: 'Estado (UF)',
    cityLabel: 'Cidade / Município',
    postalCodeLabel: 'CEP',
    hasPostalCode: true,
    addressLine2Label: 'Complemento (Apto, Bloco, Casa…)',
    states: [
      'Acre',
      'Alagoas',
      'Amapá',
      'Amazonas',
      'Bahia',
      'Ceará',
      'Distrito Federal',
      'Espírito Santo',
      'Goiás',
      'Maranhão',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Pará',
      'Paraíba',
      'Paraná',
      'Pernambuco',
      'Piauí',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondônia',
      'Roraima',
      'Santa Catarina',
      'São Paulo',
      'Sergipe',
      'Tocantins',
    ],
  },
  {
    code: 'CO', name: 'Colombia', flag: '🇨🇴', dialCode: '+57',
    idTypes: [
      { value: 'CC', label: 'Cédula de Ciudadanía' },
      { value: 'CE', label: 'Cédula de Extranjería' },
      { value: 'NIT', label: 'NIT' },
      { value: 'PASAPORTE', label: 'Pasaporte' },
    ],
    idPlaceholder: '1.234.567.890',
    idMask: 'numeric',
    stateLabel: 'Departamento',
    cityLabel: 'Ciudad / Municipio',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Apto / Torre / Oficina',
    states: [
      'Amazonas',
      'Antioquia',
      'Arauca',
      'Atlántico',
      'Bolívar',
      'Boyacá',
      'Caldas',
      'Caquetá',
      'Casanare',
      'Cauca',
      'Cesar',
      'Chocó',
      'Córdoba',
      'Cundinamarca',
      'Guainía',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Nariño',
      'Norte de Santander',
      'Putumayo',
      'Quindío',
      'Risaralda',
      'San Andrés',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupés',
      'Vichada',
    ],
  },
  {
    code: 'MX', name: 'México', flag: '🇲🇽', dialCode: '+52',
    idTypes: [
      { value: 'CURP', label: 'CURP' },
      { value: 'RFC', label: 'RFC' },
      { value: 'INE', label: 'Credencial INE' },
      { value: 'PASAPORTE', label: 'Pasaporte' },
    ],
    idPlaceholder: 'ABCD123456HDFGHI01',
    idMask: 'alphanumeric',
    stateLabel: 'Estado',
    cityLabel: 'Ciudad / Municipio / Alcaldía',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Interior / Depto',
    states: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Ciudad de México',
      'Coahuila',
      'Colima',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'México',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas',
    ],
  },
  {
    code: 'PE', name: 'Perú', flag: '🇵🇪', dialCode: '+51',
    idTypes: [
      { value: 'DNI', label: 'DNI' },
      { value: 'RUC', label: 'RUC' },
      { value: 'CE', label: 'Carnet de Extranjería' },
      { value: 'PASAPORTE', label: 'Pasaporte' },
    ],
    idPlaceholder: '12345678',
    idMask: 'numeric',
    stateLabel: 'Departamento',
    cityLabel: 'Ciudad / Distrito',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Dpto / Piso / Int.',
    states: [
      'Amazonas',
      'Áncash',
      'Apurímac',
      'Arequipa',
      'Ayacucho',
      'Cajamarca',
      'Callao',
      'Cusco',
      'Huancavelica',
      'Huánuco',
      'Ica',
      'Junín',
      'La Libertad',
      'Lambayeque',
      'Lima',
      'Loreto',
      'Madre de Dios',
      'Moquegua',
      'Pasco',
      'Piura',
      'Puno',
      'San Martín',
      'Tacna',
      'Tumbes',
      'Ucayali',
    ],
  },
  {
    code: 'ES', name: 'España', flag: '🇪🇸', dialCode: '+34',
    idTypes: [
      { value: 'DNI', label: 'DNI' },
      { value: 'NIE', label: 'NIE' },
      { value: 'CIF', label: 'CIF' },
      { value: 'PASAPORTE', label: 'Pasaporte' },
    ],
    idPlaceholder: '12345678A',
    idMask: 'alphanumeric',
    stateLabel: 'Provincia',
    cityLabel: 'Ciudad / Municipio',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Piso / Puerta / Escalera',
    states: [
      'Álava',
      'Albacete',
      'Alicante',
      'Almería',
      'Asturias',
      'Ávila',
      'Badajoz',
      'Barcelona',
      'Burgos',
      'Cáceres',
      'Cádiz',
      'Cantabria',
      'Castellón',
      'Ciudad Real',
      'Córdoba',
      'A Coruña',
      'Cuenca',
      'Girona',
      'Granada',
      'Guadalajara',
      'Guipúzcoa',
      'Huelva',
      'Huesca',
      'Islas Baleares',
      'Jaén',
      'León',
      'Lleida',
      'Lugo',
      'Madrid',
      'Málaga',
      'Murcia',
      'Navarra',
      'Ourense',
      'Palencia',
      'Las Palmas',
      'Pontevedra',
      'La Rioja',
      'Salamanca',
      'Santa Cruz de Tenerife',
      'Segovia',
      'Sevilla',
      'Soria',
      'Tarragona',
      'Teruel',
      'Toledo',
      'Valencia',
      'Valladolid',
      'Vizcaya',
      'Zamora',
      'Zaragoza',
    ],
  },
  {
    code: 'UY', name: 'Uruguay', flag: '🇺🇾', dialCode: '+598',
    idTypes: [{ value: 'CI', label: 'Cédula de Identidad' }, { value: 'PASAPORTE', label: 'Pasaporte' }],
    idPlaceholder: '1.234.567-8',
    idMask: 'numeric',
    stateLabel: 'Departamento',
    cityLabel: 'Ciudad / Localidad',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Apto / Casa',
    states: [
      'Artigas',
      'Canelones',
      'Cerro Largo',
      'Colonia',
      'Durazno',
      'Flores',
      'Florida',
      'Lavalleja',
      'Maldonado',
      'Montevideo',
      'Paysandú',
      'Río Negro',
      'Rivera',
      'Rocha',
      'Salto',
      'San José',
      'Soriano',
      'Tacuarembó',
      'Treinta y Tres',
    ],
  },
  {
    code: 'EC', name: 'Ecuador', flag: '🇪🇨', dialCode: '+593',
    idTypes: [
      { value: 'CI', label: 'Cédula de Identidad' },
      { value: 'RUC', label: 'RUC' },
      { value: 'PASAPORTE', label: 'Pasaporte' },
    ],
    idPlaceholder: '1234567890',
    idMask: 'numeric',
    stateLabel: 'Provincia',
    cityLabel: 'Ciudad / Cantón',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Depto / Piso',
    states: [
      'Azuay',
      'Bolívar',
      'Cañar',
      'Carchi',
      'Chimborazo',
      'Cotopaxi',
      'El Oro',
      'Esmeraldas',
      'Galápagos',
      'Guayas',
      'Imbabura',
      'Loja',
      'Los Ríos',
      'Manabí',
      'Morona Santiago',
      'Napo',
      'Orellana',
      'Pastaza',
      'Pichincha',
      'Santa Elena',
      'Santo Domingo',
      'Sucumbíos',
      'Tungurahua',
      'Zamora Chinchipe',
    ],
  },
  {
    code: 'BO', name: 'Bolivia', flag: '🇧🇴', dialCode: '+591',
    idTypes: [{ value: 'CI', label: 'Cédula de Identidad' }, { value: 'PASAPORTE', label: 'Pasaporte' }],
    idPlaceholder: '1234567',
    idMask: 'numeric',
    stateLabel: 'Departamento',
    cityLabel: 'Ciudad / Municipio',
    postalCodeLabel: 'Código postal',
    hasPostalCode: false,
    addressLine2Label: 'Depto / Piso',
    states: [
      'Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potosí', 'Santa Cruz', 'Tarija',
    ],
  },
  {
    code: 'PY', name: 'Paraguay', flag: '🇵🇾', dialCode: '+595',
    idTypes: [{ value: 'CI', label: 'Cédula de Identidad' }, { value: 'RUC', label: 'RUC' }, {
      value: 'PASAPORTE',
      label: 'Pasaporte',
    }],
    idPlaceholder: '1234567',
    idMask: 'numeric',
    stateLabel: 'Departamento',
    cityLabel: 'Ciudad / Distrito',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Dpto / Piso',
    states: [
      'Alto Paraguay',
      'Alto Paraná',
      'Amambay',
      'Boquerón',
      'Caaguazú',
      'Caazapá',
      'Canindeyú',
      'Central',
      'Concepción',
      'Cordillera',
      'Guairá',
      'Itapúa',
      'Misiones',
      'Ñeembucú',
      'Paraguarí',
      'Presidente Hayes',
      'San Pedro',
      'Asunción',
    ],
  },
  {
    code: 'VE', name: 'Venezuela', flag: '🇻🇪', dialCode: '+58',
    idTypes: [
      { value: 'CI', label: 'Cédula de Identidad' },
      { value: 'RIF', label: 'RIF' },
      { value: 'PASAPORTE', label: 'Pasaporte' },
    ],
    idPlaceholder: 'V-12345678',
    idMask: 'alphanumeric',
    stateLabel: 'Estado',
    cityLabel: 'Ciudad / Municipio',
    postalCodeLabel: 'Código postal',
    hasPostalCode: false,
    addressLine2Label: 'Apto / Piso / Sector',
    states: [
      'Amazonas',
      'Anzoátegui',
      'Apure',
      'Aragua',
      'Barinas',
      'Bolívar',
      'Carabobo',
      'Cojedes',
      'Delta Amacuro',
      'Distrito Capital',
      'Falcón',
      'Guárico',
      'La Guaira',
      'Lara',
      'Mérida',
      'Miranda',
      'Monagas',
      'Nueva Esparta',
      'Portuguesa',
      'Sucre',
      'Táchira',
      'Trujillo',
      'Yaracuy',
      'Zulia',
    ],
  },
  {
    code: 'PA', name: 'Panamá', flag: '🇵🇦', dialCode: '+507',
    idTypes: [{ value: 'CIP', label: 'Cédula de Identidad' }, { value: 'PASAPORTE', label: 'Pasaporte' }],
    idPlaceholder: '8-123-4567',
    idMask: 'alphanumeric',
    stateLabel: 'Provincia',
    cityLabel: 'Ciudad / Distrito',
    postalCodeLabel: 'Código postal',
    hasPostalCode: false,
    addressLine2Label: 'Apto / Edificio',
    states: [
      'Bocas del Toro',
      'Chiriquí',
      'Coclé',
      'Colón',
      'Darién',
      'Emberá',
      'Guna Yala',
      'Herrera',
      'Los Santos',
      'Ngäbe-Buglé',
      'Panamá',
      'Panamá Oeste',
      'Veraguas',
    ],
  },
  {
    code: 'CR', name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506',
    idTypes: [{ value: 'CI', label: 'Cédula de Identidad' }, { value: 'DIMEX', label: 'DIMEX' }, {
      value: 'PASAPORTE',
      label: 'Pasaporte',
    }],
    idPlaceholder: '1-1234-5678',
    idMask: 'alphanumeric',
    stateLabel: 'Provincia',
    cityLabel: 'Cantón / Distrito',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Casa / Apto',
    states: [
      'Alajuela', 'Cartago', 'Guanacaste', 'Heredia', 'Limón', 'Puntarenas', 'San José',
    ],
  },
  {
    code: 'DO', name: 'Rep. Dominicana', flag: '🇩🇴', dialCode: '+1',
    idTypes: [{ value: 'CEDULA', label: 'Cédula' }, { value: 'PASAPORTE', label: 'Pasaporte' }],
    idPlaceholder: '001-1234567-8',
    idMask: 'alphanumeric',
    stateLabel: 'Provincia',
    cityLabel: 'Ciudad / Municipio',
    postalCodeLabel: 'Código postal',
    hasPostalCode: true,
    addressLine2Label: 'Apto / Suite',
    states: [
      'Azua',
      'Bahoruco',
      'Barahona',
      'Dajabón',
      'Distrito Nacional',
      'Duarte',
      'El Seibo',
      'Elías Piña',
      'Espaillat',
      'Hato Mayor',
      'Hermanas Mirabal',
      'Independencia',
      'La Altagracia',
      'La Romana',
      'La Vega',
      'María Trinidad Sánchez',
      'Monseñor Nouel',
      'Monte Cristi',
      'Monte Plata',
      'Pedernales',
      'Peravia',
      'Puerto Plata',
      'Samaná',
      'San Cristóbal',
      'San José de Ocoa',
      'San Juan',
      'San Pedro de Macorís',
      'Sánchez Ramírez',
      'Santiago',
      'Santiago Rodríguez',
      'Santo Domingo',
      'Valverde',
    ],
  },
]
